service: rollup-detection
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline

functions:
  rollup-detector:
    description: Detect rollups with a rolling window
    handler: tasks/detect-rollups.handler
    timeout: 900
    environment:
      PROVIDER_API_KEY: ${env:PROVIDER_API_KEY}
      SUPABASE_URL: ${env:SUPABASE_URL}
      SUPABASE_API_KEY: ${env:SUPABASE_API_KEY}
      SIGNER_PRIVATE_KEY: ${env:SIGNER_PRIVATE_KEY}
    events:
      - schedule:
          rate: rate(1 minute)
          name: ${self:service}-${opt:stage}-1m-interval-trigger-detect-rollups
          description: Trigger rollup detector
          enabled: true
