-- create table for rollups

create table rollups (
  id bigint generated by default as identity primary key,
  detected_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  admin varchar(42) not null,
  proposer varchar(42) not null,
  batcher varchar(42) not null,
  sequencer varchar(42) not null,
  l1_start_time integer not null,
  l1_chain_name text not null,
  block_hash text not null,
  contracts JSON not null,
  contracts_hash text not null
);

CREATE UNIQUE INDEX rollup_contracts_hash_index
ON rollups(contracts_hash);
